// <auto-generated />
namespace EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TT));
        
        string IMigrationMetadata.Id
        {
            get { return "201308200129539_TT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
