// <auto-generated />
namespace EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class aa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aa));
        
        string IMigrationMetadata.Id
        {
            get { return "201312020736196_aa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
