// <auto-generated />
namespace EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class all : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(all));
        
        string IMigrationMetadata.Id
        {
            get { return "201312170616366_all"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
