// <auto-generated />
namespace EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class addsupd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsupd));
        
        string IMigrationMetadata.Id
        {
            get { return "201403210947531_addsupd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
